from .alex import ALEX_SYSTEM_PROMPT
from .bob import BOB_SYSTEM_PROMPT
from .david import DAVID_SYSTEM_PROMPT
from .emma import EMMA_SYSTEM_PROMPT
from .iris import IRIS_SYSTEM_PROMPT
from .mike import MIKE_SYSTEM_PROMPT

SYSTEM_PROMPTS = {
    'Mike': MIKE_SYSTEM_PROMPT,
    'Emma': EMMA_SYSTEM_PROMPT,
    'Bob': BOB_SYSTEM_PROMPT,
    'Alex': ALEX_SYSTEM_PROMPT,
    'David': DAVID_SYSTEM_PROMPT,
    'Iris': IRIS_SYSTEM_PROMPT,
}

__all__ = [
    'ALEX_SYSTEM_PROMPT',
    'BOB_SYSTEM_PROMPT',
    'DAVID_SYSTEM_PROMPT',
    'EMMA_SYSTEM_PROMPT',
    'IRIS_SYSTEM_PROMPT',
    'MIKE_SYSTEM_PROMPT',
    'SYSTEM_PROMPTS',
]
